### ISSUE TITLE
Creating Individual Contribution Report - Milestone 2

### ISSUE THREAD

**Issue by kubraaksux** [bounswe/bounswe2023group1#226]
Create a contribution report for the Practice App summarizing individual work. 
Include brief information about 

- [x] The external API(s) used, 
- [x] Details of implemented API functions, 
- [x] UI description 
- [x] Sample calls: Show a transcript of a request and response for the API functions you used and that you provide. The transcript should include the request and the detailed response (headers, status code, json etc.)
- [x] Challenges encountered
- [x] Links to important issues (git issues) and wiki documentation related to practice application
- [x ] Description of unit tests. Code fragments included to illustrate.

 The report will focus on individual contributions of mine and provide a comprehensive overview of the work done.

**Comment by kubraaksux** [comment]
done.
